<a href="https://colab.research.google.com/github/roscibely/Artificial-Intelligence-Course/blob/main/Deep_Learning_Overview_Experiment_Guide_Parte_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Description



This experiment guide introduces the following four experiments:

- **Experiment 1**: TensorFlow basics
  - This experiment mainly describes the basic syntax of TensorFlow 2.
- **Experiment 2**: common modules of TensorFlow 2
  - This experiment mainly introduces Keras interfaces.
- **Experiment 3**: handwritten text recognition
  - This experiment uses basic code to help learners understand how to implement handwritten text recognition through TensorFlow 2.0.
- **Experiment 4**: Image Classification
  - This experiment is based on how to use TensorFlow 2 and python packages to predict image categories from CIFAR10 image classification dataset. It is hoped that trainees or readers can get started with deep learning and have the basic programming capability of implementing image recognition models.


# 1 TensorFlow 2.x Basics

## 1.1 Introduction

### 1.1.1 About this experiment

This experiment helps trainees understand the basic syntax of **TensorFlow 2.x**
 by introducing a series of tensor operations of TensorFlow 2.x, including tensor creation, slicing, and indexing, tensor dimension modification, tensor arithmetic operations, and tensor sorting.

### 1.1.2 Objectives

Upon completion of this task, you will be able to:

- Understand how to create a tensor.
- Master the tensor slicing and indexing methods.
- Master the syntax for tensor dimension modification.
- Master arithmetic operations of tensors.
- Master the tensor sorting method.
- Dive deeper into eager execution and AutoGraph based on code.


## 1.2 Experiment Steps

### 1.2.1 Introduction to tensors

In TensorFlow, **tensors** are classified into **constant tensors** and **variable tensors**.

A defined constant tensor has an unchangeable value and dimension, and a defined variable tensor has a changeable value and an unchangeable dimension.
In neural networks, variable tensors are generally used as matrices for storing weights and other information, and are a type of trainable data. Constant tensors can be used as variables for storing hyperparameters or other structured data.


#### 1.2.1.1 Tensor Creation

##### 1.2.1.1.1 Creating a Constant Tensor

Common methods for creating a constant tensor include:

- **tf.constant()**: creates a constant tensor.
- **tf.zeros(), tf.zeros_like(), tf.ones(), and tf.ones_like()**: create an all-zero or all-one constant tensor.
- **tf.fill()**: creates a tensor with a user-defined value.
- **tf.random**: creates a tensor with a known distribution.

Creating a list object by using NumPy, and then converting the list object into a tensor by using **tf.convert_to_tensor**.

```python
tf.constant()
tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)
```

- **value**: value
- **dtype**: data type
- **shape**: tensor shape
- **name**: constant name
- **verify_shape**: Boolean value, used to verify the shape of a value. The default value is False. If **verify_shape** is set to **True**, the system checks whether the shape of a value is consistent with the value of shape. If they are inconsistent, the system reports an error.


In [ ]:
import tensorflow as tf

print(tf.__version__)

2.3.0


In [ ]:
# Create a 2x2 matrix with values 1, 2, 3, and 4.
const_a = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32) 
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
#View common attributes.
print("value of the constant const_a:", const_a.numpy())
print("data type of the constant const_a:", const_a.dtype)
print("shape of the constant const_a:", const_a.shape)
print("name of the device that is to generate the constant const_a:", const_a.device)

value of the constant const_a: [[1. 2.]
 [3. 4.]]
data type of the constant const_a: <dtype: 'float32'>
shape of the constant const_a: (2, 2)
name of the device that is to generate the constant const_a: /job:localhost/replica:0/task:0/device:CPU:0


tf.zeros(), tf.zeros_like(), tf.ones(), and tf.ones_like()

Usages of **tf.ones()** and **tf.ones_like()** are similar to those of **tf.zeros()** and **tf.zeros_like()**. Therefore, the following describes only the usages of **tf.ones()** and **tf.ones_like()**.

Create a constant with the value 0.
```python
tf.zeros(shape, dtype=tf.float32, name=None)
```

- **shape**: tensor shape
- **dtype**: data type
- **name**: constant name




In [ ]:
# Create a 2x3 matrix with all values being 0
zeros_b = tf.zeros(shape=[2, 3], dtype=tf.int32) 

Create a tensor whose value is 0 based on the input tensor, with its shape being the same as that of the input tensor. 

```python
tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
```

- **input_tensor**: tensor
- **dtype**: data type
- **name**: tensor name
- **optimize**: indicates whether optimization is enabled.

In [ ]:
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
zeros_like_c = tf.zeros_like(const_a)
#View generated data.
zeros_like_c.numpy()

array([[0., 0.],
       [0., 0.]], dtype=float32)

tf.fill()

Create a tensor and fill it with a specific value. 

```python
tf.fill(dims, value, name=None)
```

- **dims**: tensor shape, same as shape above.
- **value**: tensor value
- **name**: tensor name


In [ ]:
# Create a 2x3 matrix with all values being 8.
fill_d = tf.fill([3,3], 8) 
#View data.
fill_d.numpy()


array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]], dtype=int32)

tf.random

This module is used to generate a tensor with a specific distribution. Common methods in this module include **tf.random.uniform()**, **tf.random.normal()**, and **tf.random.shuffle()**. The following describes how to use **tf.random.normal()**.

Create a tensor that conforms to a normal distribution. 

```python
tf.random.normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32,seed=None, name=None)
```

- **shape**: data shape
- **mean**: mean value with a Gaussian distribution
- **stddev**: standard deviation with a Gaussian distribution
- **dtype**: data type
- **seed**: random seed
- **name**: tensor name


In [ ]:
random_e = tf.random.normal([5,5],mean=0,stddev=1.0, seed = 1)
#View the created data.
random_e.numpy()


array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

Create a list object by using NumPy, and then convert the list object into a tensor by using **tf.convert_to_tensor**.

This method can convert a given value into a tensor. **tf.convert_to_tensor** can be used to convert a Python data type into a tensor data type available to TensorFlow.

```python
tf.convert_to_tensor(value,dtype=None,dtype_hint=None,name=None)
```

- **value**: value to be converted
- **dtype**: data type of the tensor
- **dtype_hint**: optional element type for the returned tensor, used when **dtype** is set to **None**. In some cases, a caller may not consider **dtype** when calling **tf.convert_to_tensor**. Therefore, **dtype_hint** can be used as a preference.


In [ ]:
#Create a list.
list_f = [1,2,3,4,5,6]
#View the data type.
type(list_f)

list

In [ ]:
tensor_f = tf.convert_to_tensor(list_f, dtype=tf.float32)
tensor_f

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

##### 1.2.1.1.2 Creating a Variable Tensor


In TensorFlow, variables are operated using the **tf.Variable** class. **tf.Variable** indicates a tensor. The value of **tf.Variable** can be changed by running an arithmetic operation on **tf.Variable**. Variable values can be read and changed.


In [ ]:
#Create a variable. Only the initial value needs to be provided.
var_1 = tf.Variable(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
#Read the variable value.
print("Value of the variable var_1:",var_1.read_value())

#Assign a variable value.
var_value_1=[[1,2,3],[4,5,6]] 
var_1.assign(var_value_1)
print("Value of the variable var_1 after the assignment:",var_1.read_value())

Value of the variable var_1: tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Value of the variable var_1 after the assignment: tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [ ]:
#Variable addition
var_1.assign_add(tf.ones([2,3]))
var_1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

#### 1.2.1.2 Tensor Slicing and Indexing

##### 1.2.1.2.1 Slicing

Tensor slicing methods include:

- **[start: end]**: extracts a data slice from the start position to the end position of the tensor.
- **[start:end:step]** or **[::step]**: extracts a data slice at an interval of step from the start position to the end position of the tensor.
- **[::-1]**: slices data from the last element.
- **'...'**: indicates a data slice of any length.


In [ ]:
#Create a 4-dimensional tensor. The tensor contains four images. The size of each image is 100 x 100 x 3.
tensor_h = tf.random.normal([4,100,100,3])
tensor_h

In [ ]:
#Extract the first image.
tensor_h[0,:,:,:]
# hint: see the shape of result 

In [ ]:
#Extract one slice at an interval of two images.
tensor_h[::2,...]

TensorShape([2, 100, 100, 3])

In [ ]:
#Slice data from the last element.
tensor_h[::-1]

TensorShape([4, 100, 100, 3])

##### 1.2.1.2.2 Indexing

The basic format of an index is **a[d1][d2][d3]**.


In [ ]:
#Obtain the pixel in the position [20,40] in the second channel of the first image.
tensor_h[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=1.7814236>

If the indexes of data to be extracted are nonconsecutive, **tf.gather** and **tf.gather_nd** are commonly used for data extraction in TensorFlow.
To extract data from a particular dimension: 

```python
tf.gather(params, indices,axis=None)
```

- **params**: input tensor
- **indices**: index of the data to be extracted
- **axis**: dimension of the data to be extracted



In [ ]:
#Extract the first, second, and fourth images from tensor_h ([4,100,100,3]).
indices = [0,1,3]
tf.gather(tensor_h,axis=0,indices=indices,batch_dims=1)

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[ 0.32674384, -0.0766339 , -1.0805942 ],
         [ 1.0051562 ,  0.11880254,  1.1746365 ],
         [ 1.1302125 ,  0.9227219 ,  0.70335895],
         ...,
         [ 1.2145972 ,  0.8031098 , -1.2512383 ],
         [-1.5134068 ,  0.36616752,  0.15188749],
         [-0.12658004, -0.67423785, -0.45349342]],

        [[-2.3684173 , -0.13850622, -1.4001801 ],
         [ 1.5064147 ,  0.5186991 ,  0.6724327 ],
         [ 1.1000955 ,  0.95226055,  0.06054516],
         ...,
         [ 1.3575693 , -1.4204434 , -0.6551926 ],
         [ 2.900911  , -0.6555628 , -0.23319985],
         [ 0.9000248 ,  0.484177  ,  0.06844627]],

        [[ 0.15025865,  2.2596526 , -0.56073356],
         [ 0.81241566, -0.4644312 , -0.00741991],
         [ 1.6201879 , -2.5511687 ,  0.13465498],
         ...,
         [-1.0084683 , -0.2511998 ,  1.535799  ],
         [-0.5749807 , -0.20904419,  0.9182491 ],
         [-0.19500062, -1.0954205 , -0.5382607

**tf.gather_nd** allows data extraction from multiple dimensions:

```python
tf.gather_nd(params,indices)
```

- **params**: input tensor
- **indices**: indexes of the data to be extracted, which is generally a multidimensional list.

In [ ]:
#Extract the pixel in [1,1] from the first dimension of the first image and the pixel 
# in [2,2] from the first dimension of the second image in tensot_h ([4,100,100,3]).
indices = [[0,1,1,0],[1,2,2,0]]
tf.gather_nd(tensor_h,indices=indices)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5064147, 1.1839081], dtype=float32)>

#### 1.2.1.3 Tensor Dimension Modification

##### 1.2.1.3.1 Dimension Display

In [ ]:
const_d_1 = tf.constant([[1, 2, 3, 4]],shape=[2,2], dtype=tf.float32)
#Three common methods for displaying a dimension:
print(const_d_1.shape)
print(const_d_1.get_shape())
#The output is a tensor. The value of the tensor indicates the size of the tensor dimension to be displayed.
print(tf.shape(const_d_1))

(2, 2)
(2, 2)
tf.Tensor([2 2], shape=(2,), dtype=int32)


As described above, **.shape** and **.get_shape()** return TensorShape objects, and **tf.shape(x)** returns Tensor objects.

##### 1.2.1.3.2 Dimension Reshaping

```python
tf.reshape(tensor,shape,name=None)
```

- **tensor**: input tensor
- **shape**: dimension of the reshaped tensor


In [ ]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])
print(reshape_1)
tf.reshape(reshape_1, (3,2))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

##### 1.2.1.3.3 Dimension Expansion

```python
tf.expand_dims(input,axis,name=None)
```

- **input**: input tensor
- **axis**: adds a dimension after the axis dimension. When the number of dimensions of the input data is D, the axis must fall in the range of [–(D + 1), D] (included). A negative value indicates adding a dimension in reverse order.


In [ ]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
expand_sample_1 = tf.random.normal([100,100,3], seed=1)
print("size of the original data:",expand_sample_1.shape)
print("add a dimension before the first dimension (axis = 0): ",tf.expand_dims(expand_sample_1, axis=0).shape)
print("add a dimension before the second dimension (axis = 1): ",tf.expand_dims(expand_sample_1, axis=1).shape)
print("add a dimension after the last dimension (axis = –1): ",tf.expand_dims(expand_sample_1, axis=-1).shape)


size of the original data: (100, 100, 3)
add a dimension before the first dimension (axis = 0):  (1, 100, 100, 3)
add a dimension before the second dimension (axis = 1):  (100, 1, 100, 3)
add a dimension after the last dimension (axis = –1):  (100, 100, 3, 1)


##### 1.2.1.3.4 Dimension Squeezing

```python
tf.squeeze(input,axis=None,name=None)
```

- **input**: input tensor
- **axis**: If **axis** is set to 1, dimension 1 needs to be deleted.


In [ ]:
#Generate a 100 x 100 x 3 tensor to represent a 100 x 100 three-channel color image.
squeeze_sample_1 = tf.random.normal([1,100,100,3])
print("size of the original data:",squeeze_sample_1.shape)
squeezed_sample_1 = tf.squeeze(expand_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)

size of the original data: (1, 100, 100, 3)
data size after dimension squeezing: (100, 100, 3)


##### 1.2.1.3.5 Transpose

```python
tf.transpose(a,perm=None,conjugate=False,name='transpose')
```

- **a**: input tensor
- **perm**: tensor size sequence, generally used to transpose high-dimensional arrays
- **conjugate**: indicates complex number transpose.
- **name**: tensor name


In [ ]:
#Input the tensor to be transposed, and call tf.transpose.
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("size of the original data:",trans_sample_1.shape)
transposed_sample_1 = tf.transpose(trans_sample_1)
print("size of transposed data:",transposed_sample_1.shape)

size of the original data: (2, 3)
size of transposed data: (3, 2)


**perm** is required for high-dimensional data transpose, and indicates the dimension sequence of the input tensor.
The original dimension sequence of a three-dimensional tensor is [0, 1, 2] (perm), indicating the length, width, and height of high-dimensional data, respectively.
Data dimensions can be transposed by changing the sequence of values in **perm**.



In [ ]:
#Generate an $ x 100 x 200 x 3 tensor to represent four 100 x 200 three-channel color images.
trans_sample_2 = tf.random.normal([4,100,200,3])
print("size of the original data:",trans_sample_2.shape)

#Exchange the length and width for the four images: The original perm value is [0,1,2,3], and the new perm value is [0,2,1,3].
transposed_sample_2 = tf.transpose(trans_sample_2,[0,2,1,3])
print("size of transposed data:",transposed_sample_2.shape)


size of the original data: (4, 100, 200, 3)
size of transposed data: (4, 200, 100, 3)


##### 1.2.1.3.6 Broadcast (broadcast_to)

**broadcast_to** is used to broadcast data from a low dimension to a high dimension.

```python
tf.broadcast_to(input,shape,name=None)
```

- **input**: input tensor
- **shape**: size of the output tensor


In [ ]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data:",broadcast_sample_1.numpy())
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[4,6])
print("broadcasted data:",broadcasted_sample_1.numpy())

original data: [1 2 3 4 5 6]
broadcasted data: [[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [ ]:
#During the operation, if two arrays have different shapes, TensorFlow automatically triggers the broadcast mechanism as NumPy does.
a = tf.constant([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = tf.constant([1,2,3])
print(a + b)

tf.Tensor(
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]], shape=(4, 3), dtype=int32)


#### 1.2.1.4 Arithmetic Operations on Tensors

##### 1.2.1.4.1 Arithmetic Operators

Main arithmetic operations include addition (**tf.add**), subtraction (**tf.subtract**), multiplication (**tf.multiply**), division (**tf.divide**), logarithm (**tf.math.log**), and powers (**tf.pow**). The following describes only one addition example.


In [ ]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])
print(tf.add(a, b))

##### 1.2.1.4.2 Matrix Multiplication

Matrix multiplication is implemented by calling **tf.matmul**.


In [ ]:
tf.matmul(a,b)

##### 1.2.1.4.3 Tensor Statistics Collection

Methods for collecting tensor statistics include:

- **tf.reduce_min/max/mean()**: calculates the minimum, maximum, and mean values.
- **tf.argmax()/tf.argmin()**: calculates the positions of the maximum and minimum values.
- **tf.equal()**: checks whether two tensors are equal by element.
- **tf.unique()**: removes duplicate elements from tensors.
- **tf.nn.in_top_k(prediction, target, K)**: calculates whether the predicted value is equal to the actual value, and returns a Boolean tensor.
  - The following describes how to use **tf.argmax()**:
  - Return the position of the maximum value.
  - tf.argmax(input,axis):
- **input**: input tensor
- **axis**: maximum output value in the axis dimension


In [ ]:
argmax_sample_1 = tf.constant([[1,3,2],[2,5,8],[7,5,9]])
print("input tensor:",argmax_sample_1.numpy())
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by column:",max_sample_1.numpy())
print("locate the maximum value by row:",max_sample_2.numpy())


#### 1.2.1.5 Dimension-based Arithmetic Operations

In TensorFlow, a series of operations of **tf.reduce_*** reduce tensor dimensions. The series of operations can be performed on dimensional elements of a tensor, for example, calculating the mean value by row and calculating a product of all elements in the tensor.
Common operations include **tf.reduce_sum** (addition), **tf.reduce_prod** (multiplication), **tf.reduce_min** (minimum), **tf.reduce_max** (maximum), **tf.reduce_mean** (mean value), **tf.reduce_all** (logical AND), **tf.reduce_any** (logical OR), and **tf.reduce_logsumexp** (log(sum(exp))).
The methods for using these operations are similar. The following describes how to use **tf.reduce_sum**.
Calculate the sum of elements in all dimensions of a tensor.

```python
tf.reduce_sum(input_tensor, axis=None, keepdims=False,name=None)
```

- **input_tensor**: input tensor
- **axis**: axis to be calculated. If this parameter is not specified, the mean value of all elements is calculated.
- **keepdims**: indicates whether to keep dimensions. If this parameter is set to **True**, the output result retains the shape of the input tensor. If this parameter is set to **False**, dimensions of the output result decrease.
- **name**: operation name


In [ ]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("original data",reduce_sample_1.numpy())
print("calculate the sum of all elements in the tensor (axis = None): ",tf.reduce_sum(reduce_sample_1,axis=None).numpy())
print("calculate the sum of elements in each column by column (axis = 0): ",tf.reduce_sum(reduce_sample_1,axis=0).numpy())
print("calculate the sum of elements in each column by row (axis = 1): ",tf.reduce_sum(reduce_sample_1,axis=1).numpy())

original data [[1 2 3]
 [4 5 6]]
calculate the sum of all elements in the tensor (axis = None):  21
calculate the sum of elements in each column by column (axis = 0):  [5 7 9]
calculate the sum of elements in each column by row (axis = 1):  [ 6 15]


#### 1.2.1.6 Tensor Concatenation and Splitting

##### 1.2.1.6.1 Tensor Concatenation

In TensorFlow, tensor concatenation operations include:

- **tf.concat()**: concatenates vectors based on the specified dimension, while keeping other dimensions unchanged.
- **tf.stack()**: changes a group of R dimensional tensors to R+1 dimensional tensors, with the dimensions changed after the concatenation.

```python
tf.concat(values, axis, name='concat'):
```

- **values**: input tensor
- **axis**: dimension to concatenate
- **name**: operation name


In [ ]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2],axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

sizes of the original data: (4, 100, 100, 3) (40, 100, 100, 3)
size of the concatenated data: (44, 100, 100, 3)


A dimension can be added to an original matrix in the same way. axis determines the position of the dimension.

```python
tf.stack(values, axis=0, name='stack')
```

- **values**: input tensors, a group of tensors with the same shape and data type
- **axis**: dimension to concatenate
- **name**: operation name


In [ ]:
stack_sample_1 = tf.random.normal([100,100,3])
stack_sample_2 = tf.random.normal([100,100,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

sizes of the original data:  (100, 100, 3) (100, 100, 3)
size of the concatenated data: (2, 100, 100, 3)


##### 1.2.1.6.2 Tensor Splitting

In TensorFlow, tensor splitting operations include:

- **tf.unstack()**: splits a tensor by a specific dimension.
- **tf.split()**: splits a tensor into a specified number of sub tensors based on a specific dimension. **tf.split()** is more flexible than **tf.unstack()**.

```python
tf.unstack(value,num=None,axis=0,name='unstack'):
```

- **value**: input tensor
- **num**: indicates that a list containing num elements is output. The value of num must be the same as the number of elements in the specified dimension. This parameter can generally be ignored.
- **axis**: specifies the dimension based on which the tensor is split.
- **name**: operation name


In [ ]:
#Split data based on the first dimension and output the split data in a list.
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
 array([[[-1.0133315 ,  0.69181544,  0.5383482 ],
         [ 0.29377007,  1.4006099 , -0.8570871 ],
         [ 0.25680658,  0.12417778,  0.06922213],
         ...,
         [ 0.99172443, -2.0592644 ,  0.6378287 ],
         [ 0.6181454 , -0.48780182,  1.0927639 ],
         [ 0.54143643,  0.11980407, -0.93525165]],
 
        [[-0.14543562, -0.6615809 , -0.72904235],
         [ 0.03855135, -0.28938434, -0.9067116 ],
         [-0.8813679 ,  0.4625199 ,  0.02121213],
         ...,
         [-0.5034121 , -1.637174  ,  0.12363087],
         [ 1.4075073 ,  1.3478662 ,  1.161333  ],
         [ 1.2975683 , -0.8460917 , -0.6465391 ]],
 
        [[ 0.17993098,  0.63565123,  1.6273348 ],
         [-1.48286   ,  1.7690471 ,  0.5573973 ],
         [-0.02501189, -1.817492  , -0.6522744 ],
         ...,
         [-0.84101164,  0.18459934, -0.8425787 ],
         [-0.624018  , -0.82987726, -0.555089  ],
         [-0.82818466, -0.34303397, -1.8217616

```python
tf.split(value, num_or_size_splits, axis=0):
```

- **value**: input tensor
- **num_or_size_splits**: number of sub tensors
- **axis**: specifies the dimension based on which the tensor is split. **tf.split()** splits a tensor in either of the following ways:
  - If the value of **num_or_size_splits** is an integer, the tensor is evenly split into sub tensors in the specified dimension (axis = D).
  - If the value of **num_or_size_splits** is a vector, the tensor is split into sub tensors based on the element value of the vector in the specified dimension (axis = D).


In [ ]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:",np.shape(splited_sample_2[0]),np.shape(splited_sample_2[1]),np.shape(splited_sample_2[2]))


size of the original data: (10, 100, 100, 3)
size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)
sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


#### 1.2.1.7 Tensor Sorting

In TensorFlow, tensor sorting operations include:

- **tf.sort()**: sorts tensors in ascending or descending order and returns the sorted tensors.
- **tf.argsort()**: sorts tensors in ascending or descending order, and returns tensor indexes.
- **tf.nn.top_k()**: returns the first k maximum values.

```python
tf.sort/argsort(input, direction, axis)
```

- **input**: input tensor
- **direction**: sorting order, which can be set to **DESCENDING** (descending order) or **ASCENDING** (ascending order). The default value is **ASCENDING**.
- **axis**: sorting by the dimension specified by axis. The default value of axis is –1, indicating the last dimension.


In [ ]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

input tensor: [0 5 9 7 2 3 6 1 8 4]
tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]
indexes of elements in ascending order: [0 7 4 5 9 1 6 3 8 2]


```python
tf.nn.top_k(input,K,sorted=TRUE):
```

- **input**: input tensor
- **K**: the first k values to be output and their indexes
- **sorted**: When **sorted** is set to **TRUE**, the tensor is sorted in ascending order. When **sorted** is set to **FALSE**, the tensor is sorted in descending order.
  - Return two tensors:
    - **values**: k maximum values in each row
    - **indices**: positions of elements in the last dimension of the input tensor


In [ ]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())
print("first five values in ascending order:", values.numpy())
print("indexes of the first five values in ascending order:", index.numpy())

input tensor: [0 5 9 7 2 3 6 1 8 4]
first five values in ascending order: [9 8 7 6 5]
indexes of the first five values in ascending order: [2 8 3 6 1]


### 1.2.2 Eager Execution of TensorFlow 2.x

Eager execution mode:

> The eager execution mode of TensorFlow is a type of imperative programming, which is the same as native Python. When you perform a particular operation, the system immediately returns a result.

Graph mode:

> TensorFlow 1.0 adopts the graph mode to first build a computational graph, enable a session, and then feed actual data to obtain a result.


In eager execution mode, code debugging is easier, but the code execution efficiency is lower. The following implements simple multiplication by using TensorFlow to compare the differences between the eager execution mode and the graph mode.


In [ ]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [ ]:
#Use the syntax of TensorFlow 1.x in TensorFlow 2.x. 
# You can install the v1 compatibility package in TensorFlow 2.0 to 
# inherit the TensorFlow 1.x code and disable the eager execution mode.

import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#Create a graph and define it as a computational graph.
a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2],
                 [3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)
#Enable the drawing function, and perform the multiplication operation to obtain data.
with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


**Restart the kernel to restore TensorFlow 2.0** and enable the eager execution mode. Another advantage of the eager execution mode lies in availability of native Python functions, for example, the following condition statement:


In [ ]:
import tensorflow as tf

thre_1 = tf.random.uniform([],0,1)
x = tf.reshape(tf.range(0, 4), [2, 2])
print(thre_1)

if thre_1.numpy() > 0.5:
    y = tf.matmul(x, x)
else:
    y = tf.add(x, x)


tf.Tensor(0.075457454, shape=(), dtype=float32)


With the eager execution mode, this dynamic control flow can generate a NumPy value extractable by a tensor, without using operators such as **tf.cond** and **tf.while** provided in graph mode.


### 1.2.3 AutoGraph of TensorFlow 2.x

When used to comment out a function, the decorator **tf.function** can be called like any other function. **tf.function** will be compiled into a graph, so that it can run more efficiently on a GPU or TPU. In this case, the function becomes an operation in TensorFlow. The function can be directly called to output a return value. However, the function is executed in graph mode and intermediate variable values cannot be directly viewed.


In [ ]:
@tf.function
def simple_nn_layer(w,x,b):
    print(b)
    return tf.nn.relu(tf.matmul(w, x)+b)
 
w = tf.random.uniform((3, 3))
x = tf.random.uniform((3, 3))
b = tf.constant(0.5, dtype='float32')
 
simple_nn_layer(w,x,b)

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9897576, 1.32495  , 1.1061215],
       [1.2283347, 1.2863779, 1.2812262],
       [1.2245167, 1.2584676, 1.2405984]], dtype=float32)>

According to the output result, the value of **b in the function cannot be viewed directly**, but the return value can be viewed using .numpy().
The following compares the performance of the graph mode and eager execution mode by performing the same operation (computation of one CNN layer).


In [ ]:
#Use the timeit module to measure the execution time of a small code segment.
import timeit

#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))
 
#Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
    return CNN_cell(image)
 
image = tf.zeros([100, 200, 200, 3])
 
#Compare the execution time of the two modes.
CNN_cell(image)
CNN_fn(image)
#Call timeit.timeit to measure the time required for executing the code 10 times.
print("time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode:", timeit.timeit(lambda: CNN_cell(image), number=10))
print("time required for performing the computation of one CNN layer in graph mode:", timeit.timeit(lambda: CNN_fn(image), number=10))


time required for performing the computation of one convolutional neural network (CNN) layer in eager execution mode: 10.87489011999969
time required for performing the computation of one CNN layer in graph mode: 7.9776171029998295


The comparison shows that the code execution efficiency in graph mode is much higher. Therefore, the **@tf.function** function can be used to improve the code execution efficiency.
