<a href="https://colab.research.google.com/github/roscibely/Artificial-Intelligence-Course/blob/main/Deep_Learning_Overview_Experiment_Guide_Parte_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Description



This experiment guide introduces the following four experiments:

- **Experiment 1**: TensorFlow basics
  - This experiment mainly describes the basic syntax of TensorFlow 2.
- **Experiment 2**: common modules of TensorFlow 2
  - This experiment mainly introduces Keras interfaces.
- **Experiment 3**: handwritten text recognition
  - This experiment uses basic code to help learners understand how to implement handwritten text recognition through TensorFlow 2.0.
- **Experiment 4**: Image Classification
  - This experiment is based on how to use TensorFlow 2 and python packages to predict image categories from CIFAR10 image classification dataset. It is hoped that trainees or readers can get started with deep learning and have the basic programming capability of implementing image recognition models.


# 2.0 Common Modules of TensorFlow 2.x

## 2.1 Introduction

This section describes the common modules of TensorFlow 2.x, including:

- **tf.data**: implements operations on datasets. These operations include reading datasets directly from the memory, reading CSV files, reading TFRecord files, and augmenting data.
- **tf.image**: implements processing operations on images. These operations include image luminance transformation, saturation transformation, image size transformation, image rotation, and edge detection.
- **tf.gfile**: implements operations on files. These operations include reading, writing, and renaming files, and operating folders.
- **tf.keras**: a high-level API used to build and train deep learning models. 
- **tf.distributions** and other modules

This section focuses on the **tf.keras** module to lay a foundation for deep learning modeling.

## 2.2 Objectives

Upon completion of this task, you will be able to master the common deep learning modeling interfaces in **tf.keras**.


## 2.3 Experiment Steps

### 2.3.1 Model Building

#### 2.3.1.1 Stacking a Model (tf.keras.Sequential)

The most common way to build a model is to stack layers by using **tf.keras.Sequential.**

In [ ]:
import tensorflow.keras.layers as layers 
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

#### 2.3.1.2 Building a Functional Model

Functional models are mainly built by using **tf.keras.Input** and **tf.keras.Model**, which are more complex than **tf.keras.Sequential** but have a good effect. Variables can be input at the same time or in different phases, and data can be output in different phases. Functional models are preferred if more than one model output is needed.

Stacked model (.Sequential) vs. functional model (.Model):

The **tf.keras.Sequential** model is a simple stack of layers that cannot represent arbitrary models. You can use the Keras functional API to build complex model topologies such as:

- Multi-input models
- Multi-output models
- Models with shared layers
- Models with non-sequential data flows (for example, residual connections)



In [ ]:
#Use the output of the previous layer as the input of the next layer.
x = tf.keras.Input(shape=(32,))
h1 = layers.Dense(32, activation='relu')(x)
h2 = layers.Dense(32, activation='relu')(h1)
y = layers.Dense(10, activation='softmax')(h2)
model_sample_2 = tf.keras.models.Model(x, y)
 
#Print model information.
model_sample_2.summary()


Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32)]              0         
_________________________________________________________________
dense_3 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_4 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                330       
Total params: 2,442
Trainable params: 2,442
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Param numbers (32*32 weights + 32 bias)
layer1 = 32 * 32 + 32 
layer1

1056

In [ ]:
layer2 = layer1
layer3 = 32 * 10 + 10
layer3

330

#### 2.3.1.3 Building a Network Layer (tf.keras.layers)

The **tf.keras.layers** module is used to configure neural network layers. Common classes include:

- **tf.keras.layers.Dense**: builds a fully connected layer.
- **tf.keras.layers.Conv2D**: builds a two-dimensional convolutional layer.
- **tf.keras.layers.MaxPooling2D/AveragePooling2D**: builds a maximum/average pooling layer.
- **tf.keras.layers.RNN**: builds a recurrent neural network layer.
- **tf.keras.layers.LSTM/tf.keras.layers.LSTMCell**: builds an LSTM network layer/LSTM unit.
- **tf.keras.layers.GRU/tf.keras.layers.GRUCell**: builds a GRU unit/GRU network layer.
- **tf.keras.layers.Embedding**: converts a positive integer (subscript) into a vector of a fixed size, for example, converts [[4], [20]] into [[0.25, 0.1], [0.6, –0.2]]. The embedding layer can be used only as the first model layer.
- **tf.keras.layers.Dropout**: builds the dropout layer.
  - The following describes **tf.keras.layers.Dense, tf.keras.layers.Conv2D, tf.keras.layers.MaxPooling2D/AveragePooling2D**, and **tf.keras.layers.LSTM/tf.keras.layers.LSTMCell**.

Main network configuration parameters in **tf.keras.layers** include:
- **activation**: sets the activation function for the layer. By default, the system applies no activation function.
- **kernel_initializer** and **bias_initializer**: initialization schemes that create the layer's weights (kernel and bias). This defaults to the Glorot uniform initializer.
- **kernel_regularizer** and **bias_regularizer**: regularization schemes that apply to the layer's weights (kernel and bias), such as L1 or L2 regularization. By default, the system applies no regularization function.



##### 2.3.1.3.1 tf.keras.layers.Dense

Main configuration parameters in **tf.keras.layers.Dense** include:

- **units**: number of neurons
-**activation**: sets the activation function.
-**use_bias**: indicates whether to use bias terms. Bias terms are used by default.
-**kernel_initializer**: initialization scheme that creates the layer's weight (kernel)
-**bias_initializer**: initialization scheme that creates the layer's weight (bias)
-**kernel_regularizer**: regularization scheme that applies to the layer's weight (kernel)
-**bias_regularizer**: regularization scheme that applies to the layer's weight (bias)
-**activity_regularizer**: regular item applied to the output, a regularizer object
-**kernel_constraint**: a constraint applied to a weight
-**bias_constraint**: a constraint applied to a weight

In [ ]:
#Create a fully connected layer that contains 32 neurons. Set the activation function to sigmoid.
#The activation parameter can be set to a function name string, for example, sigmoid or a function object, for example, tf.sigmoid.
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
 
#Set kernel_initializer.
layers.Dense(32, kernel_initializer=tf.keras.initializers.he_normal)
#Set kernel_regularizer to L2 regularization.
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))

##### 2.3.1.3.2 tf.keras.layers.Conv2D

Main configuration parameters in tf.keras.layers.Conv2D include:

- **filters**: number of convolution kernels (output dimensions)
- **kernel_size**: width and length of a convolution kernel
-**strides**: convolution step
-**padding**: zero padding policy

When **padding** is set to **valid**, only valid convolution is performed, that is, boundary data is not processed. When **padding** is set to **same**, the convolution result at the boundary is reserved, and consequently, the output shape is usually the same as the input shape.

- **activation**: sets the activation function.
- **data_format**: data format, set to **channels_first** or **channels_last**. For example, for a 128 x 128 RGB image, data is organized as (3, 128, 128) if the value is **channels_first**, and (128, 128, 3) if the value is **channels_last**. The default value of this parameter is the value specified in **~/.keras/keras.json**. If this parameter has never been set, the default value is **channels_last**.

Other parameters include **use_bias, kernel_initializer, bias_initializer, kernel_regularizer, bias_regularizer, activity_regularizer, kernel_constraints**, and **bias_constraints**.


In [ ]:
layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

##### 2.3.1.3.3 tf.keras.layers.MaxPooling2D/AveragePooling2D


Main configuration parameters in **tf.keras.layers.MaxPooling2D/AveragePooling2D** include:

- **pool_size**: size of the pooled kernel. For example, if the matrix (2, 2) is used, the picture becomes half of the original length in both dimensions. If this parameter is set to an integer, the integer is the values of all dimensions.
- **strides**: step

Other parameters include **padding** and **data_format**.


In [ ]:
layers.MaxPooling2D(pool_size=(2,2),strides=(2,1))

##### 2.3.1.3.4 tf.keras.layers.LSTM/tf.keras.layers.LSTMCell

Main configuration parameters in **tf.keras.layers.LSTM/tf.keras.layers.LSTMCell** include:

- **units**: output dimension
- **input_shape** (**timestep** and **input_dim**): **timestep** can be set to **None**, and **input_dim** indicates the input data dimension.
- **activation**: sets the activation function.
- **recurrent_activation**: activation function to use for the recurrent step
- **return_sequences**: If the value is **True**, the system returns the full sequence. If the value is **False**, the system returns the output in the last cell of the output sequence.
- **return_state**: Boolean value, indicating whether to return the last state in addition to the output.
- **dropout**: float between 0 and 1, fraction of the neurons to drop for the linear transformation of the inputs.
- **recurrent_dropout**: float between 0 and 1, fraction of the neurons to drop for the linear transformation of the recurrent state.

In [ ]:
import numpy as np
inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=True)(inputs)
model_lstm_1 = tf.keras.models.Model(inputs=inputs, outputs=lstm)
 
inputs = tf.keras.Input(shape=(3, 1))
lstm = layers.LSTM(1, return_sequences=False)(inputs)
model_lstm_2 = tf.keras.models.Model(inputs=inputs, outputs=lstm)
 
#Sequences t1, t2, and t3
data = [[[0.1],
  [0.2],
  [0.3]]]
print(data)
print("output when return_sequences is set to True",model_lstm_1.predict(data))
print("output when return_sequences is set to False",model_lstm_2.predict(data))

[[[0.1], [0.2], [0.3]]]
output when return_sequences is set to True [[[0.01269885]
  [0.03437453]
  [0.06238829]]]
output when return_sequences is set to False [[-0.08377627]]


LSTMcell is the implementation unit of the LSTM layer.

- LSTM is an LSTM network layer.
- LSTMcell is a single-step computing unit, that is, an LSTM unit.


In [ ]:
#LSTM
tf.keras.layers.LSTM(16, return_sequences=True)
 
#LSTMCell
x = tf.keras.Input((None, 3))
y = layers.RNN(layers.LSTMCell(16))(x)

### 2.3.2 Training and Evaluation


#### 2.3.2.1 Model Compilation

After a model is built, you can call compile to configure the learning process of the model:

```python
compile( optimizer='rmsprop', loss=None, metrics=None, loss_weights=None)
```

- **optimizer**: optimizer
- **loss**: loss function, cross entropy for binary tasks and MSE for regression tasks
- **metrics**: model evaluation criteria during training and testing For example, **metrics** can be set to **['accuracy']**. To specify multiple evaluation criteria, set a dictionary, for example, set metrics to **{'output_a':'accuracy'}**.
- **loss_weights**: If the model has multiple task outputs, you need to specify a weight for each output when optimizing the global loss.


In [ ]:
model = tf.keras.Sequential()
model.add(layers.Dense(10, activation='softmax'))
#Determine the optimizer (optimizer), loss function (loss), and model evaluation method (metrics).
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

#### 2.3.2.2 Model Training

```python
fit(x=None, y=None, batch_size=None, epochs=1, verbose=1, callbacks=None, validation_split=0.0, validation_data=None, shuffle=True, class_weight=None, sample_weight=None, initial_epoch=0, steps_per_epoch=None, validation_steps=None)
```

- **x**: input training data
- **y**: target (labeled) data
- **batch_size**: number of samples for each gradient update The default value is 32.
- **epochs**: number of iteration rounds of the training model
- **verbose**: log display mode, set to 0, 1, or 2. 
  - 0: no display
  -1: progress bar
  - 2: one line for each round
- **callbacks**: callback function used during training
- **validation_split**: fraction of the training data to be used as validation data
- **validation_data**: validation set. This parameter will overwrite validation_split.
- **shuffle**: indicates whether to shuffle data before each round of iteration. This parameter is invalid when **steps_per_epoch** is not **None**. 
- **initial_epoch**: epoch at which to start training (useful for resuming a previous training weight)
- **steps_per_epoch**: set to the dataset size or **batch_size**
- **validation_steps**: Total number of steps (batches of samples) to validate before stopping. This parameter is valid only when **steps_per_epoch** is specified.



In [ ]:
import numpy as np
train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 36))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Epoch 1/10
10/10 [==============================] - 0s 15ms/step - loss: 11.8261 - categorical_accuracy: 0.0890 - val_loss: 11.8526 - val_categorical_accuracy: 0.0900
Epoch 2/10
10/10 [==============================] - 0s 3ms/step - loss: 11.8255 - categorical_accuracy: 0.0900 - val_loss: 11.8521 - val_categorical_accuracy: 0.0900
Epoch 3/10
10/10 [==============================] - 0s 3ms/step - loss: 11.8252 - categorical_accuracy: 0.0900 - val_loss: 11.8517 - val_categorical_accuracy: 0.0900
Epoch 4/10
10/10 [==============================] - 0s 3ms/step - loss: 11.8254 - categorical_accuracy: 0.0890 - val_loss: 11.8523 - val_categorical_accuracy: 0.0900
Epoch 5/10
10/10 [==============================] - 0s 3ms/step - loss: 11.8256 - categorical_accuracy: 0.0900 - val_loss: 11.8522 - val_categorical_accuracy: 0.0900
Epoch 6/10
10/10 [==============================] - 0s 3ms/step - loss: 11.8256 - categorical_accuracy: 0.0900 - val_loss: 11.8521 - val_categorical_accuracy: 0.0900
Epo

You can use **tf.data** to build training input pipelines for large datasets.

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()
 
model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset, validation_steps=3)

Epoch 1/10

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

30/30 [==============================] - 0s 4ms/step - loss: 11.8196 - categorical_accuracy: 0.0896 - val_loss: 11.7620 - val_categorical_accuracy: 0.0521
Epoch 2/10
30/30 [==============================] - 0s 1ms/step - loss: 11.8277 - categorical_accuracy: 0.0876 - val_loss: 11.7599 - val_categorical_accuracy: 0.0521
Epoch 3/10
30/30 [==============================] - 0s 1ms/step - loss: 11.8586 - categorical_accuracy: 0.0919 - val_loss: 11.7579 - val_categorical_accuracy: 0.0521
Epoch 4/10

#### 2.3.2.3 Callback Functions


A callback function is an object passed to the model to customize and extend the model's behavior during training. You can customize callback functions or use embedded functions in **tf.keras.callbacks**. Common embedded callback functions include:

- **tf.keras.callbacks.ModelCheckpoint**: periodically saves models.
- **tf.keras.callbacks.LearningRateScheduler**: dynamically changes the learning rate.
- **tf.keras.callbacks.EarlyStopping**: stops the training in advance.
- **tf.keras.callbacks.TensorBoard**: exports and visualizes the training progress and results with TensorBoard

In [ ]:
#Set hyperparameters.
Epochs = 10
 
#Define a function for dynamically setting the learning rate.
def lr_Scheduler(epoch):
    if epoch > 0.9 * Epochs:
        lr = 0.0001
    elif epoch > 0.5 * Epochs:
        lr = 0.001
    elif epoch > 0.25 * Epochs:
        lr = 0.01
    else:
        lr = 0.1
        
    print(lr)
    return lr
            
 
callbacks = [
    #Early stopping:
    tf.keras.callbacks.EarlyStopping(
        #Metric for determining whether the model performance has no further improvement
        monitor='val_loss',
        #Threshold for determining whether the model performance has no further improvement
        min_delta=1e-2,
        #Number of epochs in which the model performance has no further improvement
        patience=2),
    
    #Periodically save models.
     tf.keras.callbacks.ModelCheckpoint(
        #Model path
        filepath='testmodel_{epoch}.h5',
        #Whether to save the optimal model.
        save_best_only=True,
        #Monitored metric
        monitor='val_loss'),
    
    #Dynamically change the learning rate.
    tf.keras.callbacks.LearningRateScheduler(lr_Scheduler),
    
    #Use TensorBoard.
    tf.keras.callbacks.TensorBoard(log_dir='./logs')
]
 
model.fit(train_x, train_y, batch_size=16, epochs=Epochs,callbacks=callbacks, validation_data=(val_x, val_y))

0.1
Epoch 1/10
 1/63 [..............................] - ETA: 0s - loss: 11.8669 - categorical_accuracy: 0.2500WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
63/63 [==============================] - 0s 4ms/step - loss: 12.0383 - categorical_accuracy: 0.0890 - val_loss: 11.8999 - val_categorical_accuracy: 0.0950
0.1
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 12.0968 - categorical_accuracy: 0.0950 - val_loss: 11.9566 - val_categorical_accuracy: 0.1200
0.1
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 12.2010 - categorical_accuracy: 0.1100 - val_loss: 12.1744 - val_categorical_accuracy: 0.1200


#### 2.3.2.4 Evaluation and Prediction

Evaluation and prediction functions: **tf.keras.Model.evaluate** and **tf.keras.Model.predict**.

In [ ]:
#Model evaluation
test_x = np.random.random((1000, 36))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)

32/32 [==============================] - 0s 1ms/step - loss: 12.2724 - categorical_accuracy: 0.0890


[12.2723970413208, 0.08900000154972076]

In [ ]:
#Model prediction
pre_x = np.random.random((10, 36))
result = model.predict(test_x,)
print(result)

[[0.08740149 0.09348525 0.19208874 ... 0.11176775 0.18140036 0.06074111]
 [0.06755098 0.06422394 0.17860973 ... 0.09259084 0.21146445 0.04909515]
 [0.12066569 0.11835348 0.12646042 ... 0.15002887 0.2147491  0.03346167]
 ...
 [0.11750468 0.03414055 0.11132252 ... 0.1242044  0.23281755 0.03624053]
 [0.14516938 0.03110421 0.21943997 ... 0.17944635 0.09487376 0.03716444]
 [0.15893438 0.08574913 0.14549519 ... 0.13794138 0.12710859 0.04806716]]


### 2.3.3 Model Saving and Restoration


#### 2.3.3.1 Saving and Restoring an Entire Model


In [ ]:
import numpy as np
#Save models.
model.save('the_save_model.h5')
#Import models.
new_model = tf.keras.models.load_model('the_save_model.h5')
new_prediction = new_model.predict(test_x)
#np.testing.assert_allclose: determines whether the similarity between two objects exceeds the specified tolerance. If yes, the system displays an exception.
#atol: specified tolerance
np.testing.assert_allclose(result, new_prediction, atol=1e-6) # Prediction results are the same.

After a model is saved, you can find the corresponding weight file in the corresponding folder.


#### 2.3.3.2 Saving and Loading Network Weights Only

If the weight name is suffixed with **.h5** or **.keras**, save the weight as an HDF5 file, or otherwise, save the weight as a TensorFlow checkpoint file by default.


In [ ]:
model.save_weights('model_weights')
model.save_weights('model_weights.h5')
#Load the weights.
model.load_weights('model_weights')
model.load_weights('model_weights.h5')