<a href="https://colab.research.google.com/github/roscibely/Huawei-HCIA/blob/main/Math-Basics/Math_Basics_Experiment_Guide.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This document mainly uses the **math** library, **numpy**, and scipy library. The **math** library, a standard library of Python, provides some common mathematical functions; the **numpy** library, a numerical calculation and expansion library of Python, is mainly used to handle issues such as linear algebra, random number generation, and Fourier Transform; the **scipy** labrary is used to deal with issues such as statistics, optimization, interpolation, and bouns points. 

# 1. Basics math functions

In [2]:
import math 
import numpy as np

In [5]:
#ceil() returns the minimum integer greater than or equal to x
math.ceil(4.3)

5

In [6]:
#floor() return the maximum integer less than or equal to x 
math.floor(4.3)

4

# 2. Linear Algebra Experiment

In [7]:
#Generate a two-dimensional tensor whose elements are 0 and dimensions are 3 and 4
np.zeros((3,4)) #3 lines and 4 columns 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
#Generate a 3d random tensor with dimensions 2,3,4
np.random.rand(2,3,4)

array([[[0.36795786, 0.68137555, 0.2866637 , 0.6251878 ],
        [0.34649041, 0.34533404, 0.31232883, 0.06440583],
        [0.73646116, 0.36989571, 0.88069747, 0.32826696]],

       [[0.46886831, 0.15597468, 0.64572536, 0.09799862],
        [0.74344389, 0.24768811, 0.43767717, 0.29498896],
        [0.68034344, 0.05571075, 0.39662425, 0.67284608]]])

In [9]:
#matrix implementation 
np.mat(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

2.1 reshape Operation 

The reshape operation is used to change the dimension number of a array and size of each dimension. 


In [15]:
#Generate a vector from 0 to 11
x=np.arange(12) #also can be np.arange(1,13,1)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [16]:
x.shape

(12,)

In [18]:
#Convert the matrix x into a 2d matrix 
x=x.reshape(1,12)
print(x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


In [19]:
x.shape

(1, 12)

In [21]:
#Convert x to 3x4 matrix
x=x.reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
#Transposition implementation 
print(x.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [24]:
#Matrix multiplication 
np.matmul(x,x.T)

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [26]:
print(x*x) #is the same x**2

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [27]:
x**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [28]:
#inverse matrix
np.linalg.inv([[1, 2], [4, 6]])

array([[-3. ,  1. ],
       [ 2. , -0.5]])