<a href="https://colab.research.google.com/github/roscibely/Artificial-Intelligence-Course/blob/main/Python_Programming_Basics/TensorFlow_2x_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TensorFlow 2.x Basics


This experiment helps trainess understand the basic syntax of TensorFlow 2.x by introducing a series of tensor dimension modification, tensor arithmetic operations, and tensor sorting. 

In [4]:
import tensorflow as tf 
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [ ]:
#Creat aa 2x2 matrix
A=tf.constant([[1,2,3,4]], shape=[2,2], dtype=tf.float32)
print(A)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [ ]:
#View common attributes 
print("Value of constant A=", A.numpy())
print("Data type of A ", A.dtype)
print("Shape of A ", A.shape)
#print("Name of the device that is to generate ", A.device)

Value of constant A= [[1. 2.]
 [3. 4.]]
Data type of A  <dtype: 'float32'>
Shape of A  (2, 2)


In [ ]:
'''
tf.fill()
Create a tensor and fill it with a scalar value. 
tf.fill(dim,value, name=None)
'''
v=tf.fill([3,4],2)
print(v)

tf.Tensor(
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]], shape=(3, 4), dtype=int32)


In [ ]:
'''
tf.random 
This module is used to generate a tensor with a specific distribution. 
Common methods in this module include tf.random.uniform() tf.random.normal()
and tf.random.suffle().

tf.random.normal(shape, mean=0.0,stddev=1.0,dtype=tf.float32,seed=None,name=None)
'''

randomex= tf.random.normal([5,5], mean=0,stddev=1.0, seed=1)
randomex.numpy()

array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)

In [ ]:
'''
tf.convert_to_tensor
This method can convert a given value into a tensor. It can be used to convert a
Python data type into a tensor data type available to TensorFlow. 
'''

list_a=[1,2,3,4,5,6]
print(type(list_a))
tensor_a=tf.convert_to_tensor(list_a,dtype=tf.float32)
print(tensor_a)


<class 'list'>
tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


### Tensor Slicing and indexing 

  - Tensor slicing methods include: 
      - [start: end] extracts a data slice from the start position to the end position of the tensor. 
      - [start: end: step] or [::step] extracts a data slice at an invertval of step from the start position to the end position of the tensor. 
      - [::-1] slices data from the last element. 


In [ ]:
#Create a 4-D tensor. 
#The tensor contains 5 images. The size of each image is 100x100x3
img_tensor=tf.random.normal([5,100,100,3])
print(img_tensor)

tf.Tensor(
[[[[-5.22027552e-01 -1.58614609e-02 -1.12143278e+00]
   [-8.23308229e-01  6.64215982e-01  4.28676903e-01]
   [-1.35466027e+00 -7.14150965e-01  8.64303172e-01]
   ...
   [-6.91789448e-01  1.21845984e+00  3.53610963e-01]
   [ 7.65778780e-01  6.04217350e-01  5.93480647e-01]
   [-8.77132416e-01  1.33109510e+00 -1.50270748e+00]]

  [[ 1.71881843e+00  1.54030137e-02 -6.77529752e-01]
   [-5.28534710e-01 -1.79538820e-02  1.79677510e+00]
   [-2.41571933e-01 -3.40310484e-01 -1.41861010e+00]
   ...
   [ 1.20306706e+00  1.67937219e+00 -5.91477036e-01]
   [-1.35376871e+00 -2.73371387e+00 -8.99027884e-01]
   [-2.14445281e+00  1.63292730e+00  7.40244746e-01]]

  [[-7.10211277e-01 -1.09932053e+00 -1.86425701e-01]
   [-1.25830519e+00 -1.69960298e-02 -1.14507413e+00]
   [-1.26310848e-02 -8.64255190e-01  7.25629449e-01]
   ...
   [ 3.41245145e-01 -1.62748218e+00  2.16536093e+00]
   [ 1.89519286e+00 -1.26040375e+00  9.49279249e-01]
   [ 5.19531846e-01  2.48741913e+00  1.32785308e+00]]

  ...

 

In [ ]:
#Extract the first image
img_tensor[0,:,:,:]


<tf.Tensor: shape=(100, 100, 3), dtype=float32, numpy=
array([[[-0.52202755, -0.01586146, -1.1214328 ],
        [-0.8233082 ,  0.664216  ,  0.4286769 ],
        [-1.3546603 , -0.71415097,  0.8643032 ],
        ...,
        [-0.69178945,  1.2184598 ,  0.35361096],
        [ 0.7657788 ,  0.60421735,  0.59348065],
        [-0.8771324 ,  1.3310951 , -1.5027075 ]],

       [[ 1.7188184 ,  0.01540301, -0.67752975],
        [-0.5285347 , -0.01795388,  1.7967751 ],
        [-0.24157193, -0.34031048, -1.4186101 ],
        ...,
        [ 1.2030671 ,  1.6793722 , -0.59147704],
        [-1.3537687 , -2.7337139 , -0.8990279 ],
        [-2.1444528 ,  1.6329273 ,  0.74024475]],

       [[-0.7102113 , -1.0993205 , -0.1864257 ],
        [-1.2583052 , -0.01699603, -1.1450741 ],
        [-0.01263108, -0.8642552 ,  0.72562945],
        ...,
        [ 0.34124514, -1.6274822 ,  2.165361  ],
        [ 1.8951929 , -1.2604038 ,  0.94927925],
        [ 0.51953185,  2.4874191 ,  1.3278531 ]],

       ...,

     

In [ ]:
#Extract one slice at an interval of two images
img_tensor[::2,...]

<tf.Tensor: shape=(3, 100, 100, 3), dtype=float32, numpy=
array([[[[-5.22027552e-01, -1.58614609e-02, -1.12143278e+00],
         [-8.23308229e-01,  6.64215982e-01,  4.28676903e-01],
         [-1.35466027e+00, -7.14150965e-01,  8.64303172e-01],
         ...,
         [-6.91789448e-01,  1.21845984e+00,  3.53610963e-01],
         [ 7.65778780e-01,  6.04217350e-01,  5.93480647e-01],
         [-8.77132416e-01,  1.33109510e+00, -1.50270748e+00]],

        [[ 1.71881843e+00,  1.54030137e-02, -6.77529752e-01],
         [-5.28534710e-01, -1.79538820e-02,  1.79677510e+00],
         [-2.41571933e-01, -3.40310484e-01, -1.41861010e+00],
         ...,
         [ 1.20306706e+00,  1.67937219e+00, -5.91477036e-01],
         [-1.35376871e+00, -2.73371387e+00, -8.99027884e-01],
         [-2.14445281e+00,  1.63292730e+00,  7.40244746e-01]],

        [[-7.10211277e-01, -1.09932053e+00, -1.86425701e-01],
         [-1.25830519e+00, -1.69960298e-02, -1.14507413e+00],
         [-1.26310848e-02, -8.64255190e-01

In [ ]:
#Slice data from the least element
img_tensor[::-1]

<tf.Tensor: shape=(5, 100, 100, 3), dtype=float32, numpy=
array([[[[ 2.64212731e-02, -2.34643206e-01,  6.62149251e-01],
         [-1.59435964e+00, -5.98397076e-01, -2.21772090e-01],
         [ 1.79156673e+00, -1.25542045e+00,  5.20995498e-01],
         ...,
         [ 1.06496930e+00,  1.05994773e+00, -8.75325561e-01],
         [ 1.45803383e-02,  1.61459124e+00,  1.26058966e-01],
         [-5.93702018e-01, -8.00325692e-01,  1.13788404e-01]],

        [[ 3.68712485e-01,  2.72502840e-01,  3.77465814e-01],
         [ 4.53150868e-01,  1.86521268e+00, -1.08164239e+00],
         [-1.78706348e+00, -6.44446552e-01, -1.39235938e+00],
         ...,
         [-5.74416161e-01, -3.62926483e-01,  1.68302751e+00],
         [-1.04895897e-01,  5.11839390e-01,  1.29092526e+00],
         [-5.10088623e-01,  6.45654425e-02, -1.70379317e+00]],

        [[-3.59562755e-01, -2.97085434e-01, -9.27673995e-01],
         [-1.41100979e+00, -7.90670335e-01,  4.40572351e-01],
         [ 1.13372707e+00,  6.23011231e-01

### Indexing

In [ ]:
#The basic format of an index is a[][][]

#Obtain the pixel in the position [20,40] in the second channel of the firt image
img_tensor[0][19][39][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.19407582>

In [6]:
# Dimension Reshaping 
a=tf.constant([[1,2,3],[4,5,6]])
print(a)
tf.reshape(a,(1,6))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 2, 3, 4, 5, 6]], dtype=int32)>

In [41]:
# Transpose 
print(tf.transpose(a))

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


## AutoGraph of TensorFlow 2.x

When used to comment out a function, the decorator tf.function can be called like any other function. tf.function will be compiled into a graph, so that it can rum more efficiently on a GPU or TPU. In this case, the function becomes an operation in TensorFlow. The function can be directly called out a return value. However, the function is executed in graph mode and intermediate variable cannot be directcly viewed. 

In [42]:
@tf.function 
def simple_nn_layer(w,x,b):
  print(b)
  return tf.nn.relu(tf.matmul(w,x) +b) #layer output

w=tf.random.uniform((3,3)) #Random matrix 3x3 
x=tf.random.uniform((3,3)) #Random matrix 3x3
b=tf.constant(0.5,dtype='float32')

#call the function
simple_nn_layer(w,x,b)

'''
According to the output result, the value of b in the function cannot be
viewed directly, but the return value can be viewed using .numpy()
'''

Tensor("b:0", shape=(), dtype=float32)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.0744793, 1.0579548, 1.1227345],
       [1.5413144, 1.4187595, 1.1597376],
       [1.6831049, 1.7826493, 1.4979806]], dtype=float32)>